### ISSUE TITLE
Document how to install in project

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-java-cms#18]

**Comment by clearsky** [comment]
Hi, I've tried as an early adapter to integrate the cms to our sunrise java demo fork upgrading to 0.9.0 but I think there has to be added a configuration for        
` final Configuration config = configuration.getConfig("application.cms.i18n");`
in the application.conf for the CmsI18nResolverProvider

Do you have something prepared? Thank you in advance. 

Our Error: 
```
Error in custom provider, java.lang.NullPointerException
  while locating com.commercetools.sunrise.common.template.cms.filebased.CmsI18nResolverProvider
  at com.commercetools.sunrise.common.template.TemplateModule.configure(TemplateModule.java:22) (via modules: com.google.inject.util.Modules$OverrideModule -> com.commercetools.sunrise.common.template.TemplateModule)
  while locating com.commercetools.sunrise.common.template.i18n.I18nResolver annotated with @com.google.inject.name.Named(value=cms)
    for field at com.commercetools.sunrise.common.template.cms.filebased.FileBasedCmsService.i18nResolver(FileBasedCmsService.java:25)
  while locating com.commercetools.sunrise.common.template.cms.filebased.FileBasedCmsService
  while locating com.commercetools.sunrise.cms.CmsService
```

**Comment by lauraluiz** [comment]
@clearsky yes, you are right. To use the simple file-based CMS you need that config. There are still lots of changes involved here:
- We need to move the i18n Resolver as an external dependency: https://github.com/commercetools/commercetools-sunrise-java/issues/483
- We need to move the file-based CMS to the CMS repo, so that it also becomes an external dependency: https://github.com/commercetools/commercetools-sunrise-java/issues/484
- We have to document in that repo how to work with it (including the missing config).
- In general, we would like to provide some default config so that not all the configuration relies on the blank project (ex-demo) or your other Sunrise-based projects.

Still a lot of work to do that is directly involving this.
Thanks for all the feedback!
